[Goerli] SDVT polishing
lidofinance/easy-track-ui pull request #205
Opened 2023-11-01 21:35 UTC by katamarinaki

2023-11-02 12:00 UTC, BATMAH69 requested changes

2023-11-02 12:00 UTC, BATMAH69 commented on modules/motions/utils/validateAddress.ts
> +}
What do you think about [consistent-return](https://eslint.org/docs/latest/rules/consistent-return)?

2023-11-02 12:00 UTC, BATMAH69 commented on modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTTargetValidatorLimitsUpdate.tsx
>  import { NodeOperatorSelectControl } from '../../NodeOperatorSelectControl'
It looks like it could be imported form `'modules/...'` like others components

2023-11-02 12:00 UTC, BATMAH69 commented on modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTTargetValidatorLimitsUpdate.tsx
> +            isTargetLimitActive: targetLimit === 0 ? false : true,
I see that you get rid from `isTargetLimitActive` is it a part of agreements?

2023-11-02 12:44 UTC, BATMAH69 approved these changes

2023-11-03 16:24 UTC, closed without merging

2023-11-03 16:24 UTC, katamarinaki commented
Closed in favor of #208