Add IncreaseNodeOperatorLimit to Sandbox module on Holesky
lidofinance/easy-track-ui pull request #207
Opened 2023-11-02 13:34 UTC by katamarinaki

### Description

New motion type: SandboxNodeOperatorIncreaseLimit, new Node Operator Registry: SandboxNodeOperatorsRegistry. 

### Checklist:

- [ ] Checked the changes locally.
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2023-11-03 16:58 UTC, BATMAH69 commented
@katamarinaki could you check that logic in `useAvailableMotions.ts` with useNodeOperatorsList is correct?

2023-11-03 17:48 UTC, katamarinaki commented
@BATMAH69 thanks for pointing out the issue with `useAvailableMotions`. I did a proper refactor and added new check for sandbox module.

2023-11-03 18:29 UTC, BATMAH69 requested changes

2023-11-03 18:29 UTC, BATMAH69 commented on modules/motions/ui/MotionFormStartNew/Parts/StartNewNodeOperatorLimitIncrease.tsx
> +        currentNodeOperator && walletAddress && nodeOperators.data
it looks like `Boolean(currentNodeOperator)`, bc if `walletAddress && nodeOperators.data` is false  than `currentNodeOperator` will be null

2023-11-03 18:29 UTC, BATMAH69 commented on modules/motions/ui/MotionFormStartNew/Parts/StartNewNodeOperatorLimitIncrease.tsx
>                    if (value === '') return true
looks like `if (value === '') return true` is the same as required

2023-11-03 18:29 UTC, BATMAH69 commented on modules/motions/ui/MotionFormStartNew/Parts/StartNewNodeOperatorLimitIncrease.tsx
> +                  if (Number.isNaN(parsedValue)) return 'Wrong number format'
You could use `isNaN` here instead of `Number.isNaN`. I will work same, because you used `Number(value)` at previous line.

2023-11-06 10:42 UTC, BATMAH69 approved these changes

2023-11-29 13:57 UTC, merged